apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      containers:
        - name: central
          image: matijamaks/central:latest
          env:
            - name: PGHOST
              value: localhost
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: PGDATABASE
              value: central_db
            - name: PGPORT
              value: "5432"
          ports:
            - containerPort: 3000

        - name: central-database
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: central_db
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: central
spec:
  selector:
    app: central
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP